#!/bin/bash
REACT_DASH_REPO="https://github.com/NuCivic/react-dashboard.git"
TIMESTAMP=$( date +%s )
# use gnu sed in osx
alias sed=/usr/local/Cellar/gnu-sed/4.2.2/bin/sed
# make a backup directory
if [ ! -d backups ]; then
    echo "Creating backup directory"
    mkdir backups
fi

# if src directory exists, create backup first
if [ -d "src" ]; then
    BU_SRCDIR="backups/_src_$TIMESTAMP"
    echo "Backing up current /src dir to $BU_SRCDIR"
    mv src $BU_SRCDIR
fi

# build /src directory from react dash repo
echo "Copying boilerplate project from react-dashboard/examples"
mkdir src
cp -r node_modules/react-dash/examples/ src

# update import statements
# @@TODO - we should update react-dash lib to handle all imports via ../src/ReactDashboard then just rewrite that
echo "A"
find src -type f -exec sed -i '' -E "s/\.\.\/\.\.\/src(.*)/react-dash'/g" {} \;
echo "B"
find src -type f -exec sed -i '' -E "s/\.\.\/src(.*)/react-dash'/g" {} \;
echo "C"
#find src -type f -exec sed -i '' -E "s/import\s(\w+.*)\sfrom 'react-dash'/import { \1 } from 'react-dash'/g" {} \;
find src -type f -exec sed -i '' -E "s/import(.*)from 'react-dash'/import {\1} from 'react-dash'/g" {} \;
# rewrite "{ { library } }" as "{ library }"
find src -type f -exec sed -i '' -E "s/import { {(.*)} }/import { \1 }/g" {} \; 
# @@DEBUG- show new import statements

echo "D"
# move resources to src folder
find src -type f -exec grep 'react-dash' {} \;
echo "Moving resources to /src folder"
cp -r resources/ src/
cp lib/dist/react-dashboard.min.css src/

# add README
touch ./src/README.md
cat << EOF > ./src/README.md
This boilerplate project was generated by script at `date "+%Y-%m-%d %H:%M:%S"`
Using npm library `npm list | grep react-dash`
EOF
