#!/bin/bash
REACT_DASH_REPO_TAG=$1
REACT_DASH_REPO="https://github.com/NuCivic/react-dashboard.git"
DEST_DIR="lib"
TIMESTAMP=$( date +%s )

# make a backup directory
if [ ! -d backups ]; then
    echo "Creating backup directory"
    mkdir backups
fi

# if destination dir exists back up
if [ -d "$DEST_DIR" ]; then
    BU_DEST_DIR="backups/_$DEST_DIR_$TIMESTAMP"
    echo "Backing up current $DEST_DIR to $BU_DEST_DIR"
    mv $DEST_DIR $BU_DEST_DIR
fi

# clone react-dash
echo "Cloning React Dash into $DEST_DIR"
git clone $REACT_DASH_REPO $DEST_DIR

# checkout desired tag, if specified
if [ ! -z "$REACT_DASH_REPO_TAG" ]; then
    echo "Checking out $REACT_DASH_REPO_TAG"
    cd $DEST_DIR&&git checkout $REACT_DASH_REPO_TAG&&cd ..
fi

# if src directory exists, create backup first
if [ -d "src" ]; then
    BU_SRCDIR="backups/_src_$TIMESTAMP"
    echo "Backing up current /src dir to $BU_SRCDIR"
    mv src $BU_SRCDIR
fi

# build /src directory from react dash repo
echo "Copying boilerplate project from react-dashboard/examples"
mkdir src
cp -r $DEST_DIR/examples/ src

# update import statements
find src -type f -exec sed -i -e -E "s/\.\.\/\.\.\/src(.*)/react-dashboard'/g" {} \;
find src -type f -exec grep 'react-dashboard' {} \;
##      replace `from ../../src` style imports with import statements with  `from react-dash` style imports

# add README
touch ./src/README.md
cat << EOF > ./src/README.md
This boilerplate project was generated by script at `date "+%Y-%m-%d %H:%M:%S"`
Repo: $REACT_DASH_REPO
Tag: $REACT_DASH_REPO_TAG (or master)
EOF
