#!/bin/bash
REACT_DASH_REPO_TAG=$1
REACT_DASH_REPO="https://github.com/NuCivic/react-dashboard.git"
DEST_DIR="lib"
TIMESTAMP=$( date +%s )
alias sed=/usr/local/Cellar/gnu-sed/4.2.2/bin/sed
# make a backup directory
if [ ! -d backups ]; then
    echo "Creating backup directory"
    mkdir backups
fi

# if destination dir exists back up
if [ -d "$DEST_DIR" ]; then
    BU_DEST_DIR="backups/_$DEST_DIR_$TIMESTAMP"
    echo "Backing up current $DEST_DIR to $BU_DEST_DIR"
    mv $DEST_DIR $BU_DEST_DIR
fi

# clone react-dash
echo "Cloning React Dash into $DEST_DIR"
git clone $REACT_DASH_REPO $DEST_DIR

# checkout desired tag, if specified
if [ ! -z "$REACT_DASH_REPO_TAG" ]; then
    echo "Checking out $REACT_DASH_REPO_TAG"
    cd $DEST_DIR&&git checkout $REACT_DASH_REPO_TAG&&cd ..
fi

# if src directory exists, create backup first
if [ -d "src" ]; then
    BU_SRCDIR="backups/_src_$TIMESTAMP"
    echo "Backing up current /src dir to $BU_SRCDIR"
    mv src $BU_SRCDIR
fi

# build /src directory from react dash repo
echo "Copying boilerplate project from react-dashboard/examples"
mkdir src
cp -r $DEST_DIR/examples/ src

# update import statements
# @@TODO - we should update react-dash lib to handle all imports via ../src/ReactDashboard then just rewrite that
echo "A"
find src -type f -exec sed -i '' -E "s/\.\.\/\.\.\/src(.*)/react-dash'/g" {} \;
echo "B"
find src -type f -exec sed -i '' -E "s/\.\.\/src(.*)/react-dash'/g" {} \;
echo "C"
#find src -type f -exec sed -i '' -E "s/import\s(\w+.*)\sfrom 'react-dash'/import { \1 } from 'react-dash'/g" {} \;
find src -type f -exec sed -i '' -E "s/import(.*)from 'react-dash'/import {\1} from 'react-dash'/g" {} \;

# @@DEBUG- show new import statements

echo "D"
# move resources to src folder
find src -type f -exec grep 'react-dash' {} \;
echo "Moving resources to /src folder"
cp -r resources/ src/
cp lib/dist/react-dashboard.min.css src/

# add README
touch ./src/README.md
cat << EOF > ./src/README.md
This boilerplate project was generated by script at `date "+%Y-%m-%d %H:%M:%S"`
Repo: $REACT_DASH_REPO
Tag: $REACT_DASH_REPO_TAG (or master)
EOF
